2018-03-29 00:32:05,302 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 584546ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 00:32:05,303 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 584518ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 00:32:05,303 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 584459ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 00:32:05,304 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 584459ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 00:42:01,716 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 576402ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 00:42:01,717 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 576400ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 00:42:01,717 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 576403ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 00:42:01,718 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 576400ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 00:51:57,604 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 575869ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 00:51:57,604 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 575870ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 00:51:57,605 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 575867ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 00:51:57,607 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 575869ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 01:01:54,477 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 576855ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 01:01:54,478 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 576855ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 01:01:54,478 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 576864ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 01:01:54,480 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 576855ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 01:11:51,359 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 576869ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 01:11:51,361 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 576868ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 01:11:51,361 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 576868ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 01:11:51,362 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 576868ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 01:21:47,251 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 575877ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 01:21:47,252 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 575877ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 01:21:47,252 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 575877ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 01:21:47,253 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 575876ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 01:31:44,125 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 576858ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 01:31:44,126 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 576867ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 01:31:44,126 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 576858ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 01:31:44,127 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 576858ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 01:41:41,005 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 576864ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 01:41:41,006 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 576863ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 01:41:41,006 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 576864ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 01:41:41,007 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 576863ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 01:51:37,886 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 576869ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 01:51:37,886 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 576870ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 01:51:37,887 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 576870ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 01:51:37,889 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 576870ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 02:00:00,780 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 482884ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 02:00:00,783 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 482883ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 02:00:00,785 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 482883ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 02:00:00,789 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 482883ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 02:10:07,177 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 586325ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 02:10:07,185 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 586323ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 02:10:07,188 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 586321ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 02:10:07,188 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 586326ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 02:20:14,063 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 586783ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 02:20:14,064 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 586787ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 02:20:14,064 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 586784ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 02:20:14,065 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 586786ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 02:30:19,027 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 584894ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 02:30:19,030 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 584897ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 02:30:19,032 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 584893ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 02:30:19,032 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 584745ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 02:40:22,019 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582902ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 02:40:22,020 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582905ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 02:40:22,027 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582902ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 02:40:22,041 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582905ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 02:50:26,053 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 583980ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 02:50:26,054 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 583970ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 02:50:26,055 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 583970ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 02:50:26,055 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 583969ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 03:00:30,068 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 583952ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 03:00:30,070 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 583952ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 03:00:30,071 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 583952ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 03:00:30,072 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582623ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 03:10:33,031 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582923ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 03:10:33,034 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582899ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 03:10:33,045 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582922ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 03:10:33,045 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582922ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 03:20:36,009 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582941ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 03:20:36,013 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582940ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 03:20:36,014 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582940ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 03:20:36,015 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582939ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 03:30:39,063 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582054ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 03:30:39,065 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582976ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 03:30:39,065 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582975ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 03:30:39,068 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582055ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 03:40:44,006 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 584876ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 03:40:44,022 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 584861ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 03:40:44,022 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 584860ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 03:40:44,026 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 584861ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 03:50:47,033 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 581839ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 03:50:47,928 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 581838ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 03:50:47,929 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 581839ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 03:50:47,930 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 581838ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 04:00:50,243 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582042ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 04:00:50,264 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582042ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 04:00:50,264 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582041ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 04:00:50,266 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582042ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 04:10:52,036 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 581660ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 04:10:52,054 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 581659ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 04:10:52,056 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 580843ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 04:10:52,056 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 580843ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 04:20:55,439 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582415ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 04:20:55,441 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582416ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 04:20:55,442 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582415ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 04:20:55,446 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582415ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 04:30:58,418 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582943ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 04:30:58,418 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582943ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 04:30:58,420 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582942ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 04:30:58,421 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582942ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 04:41:00,451 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 581390ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 04:41:00,513 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 581379ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 04:41:00,521 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 581379ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 04:41:00,527 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 581378ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 04:51:03,054 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582187ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 04:51:03,060 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582186ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 04:51:03,061 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582186ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 04:51:03,061 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582186ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 05:01:05,025 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 581912ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 05:01:05,330 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 581912ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 05:01:05,369 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 581911ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 05:01:05,370 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 581912ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 05:11:07,073 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 581671ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 05:11:07,074 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 581671ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 05:11:07,078 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 581670ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 05:11:07,079 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 581670ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 05:21:10,032 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582895ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 05:21:11,002 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582894ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 05:21:11,002 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582892ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 05:21:11,003 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582893ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 05:31:13,101 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582081ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 05:31:13,416 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582082ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 05:31:13,416 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582081ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 05:31:13,417 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582082ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 05:41:15,094 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 581525ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 05:41:15,095 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 581526ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 05:41:15,095 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 580679ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 05:41:15,096 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 580678ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 05:51:18,069 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582327ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 05:51:18,070 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582327ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 05:51:18,071 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582328ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 05:51:18,071 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582328ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 06:01:21,436 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582433ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 06:01:21,503 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582421ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 06:01:21,852 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582418ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 06:01:21,853 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582396ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 06:11:24,886 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582164ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 06:11:24,888 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582165ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 06:11:24,888 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582042ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 06:11:24,889 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582043ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 06:21:26,448 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 581131ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 06:21:26,460 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 581129ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 06:21:26,466 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 581118ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 06:21:26,467 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 581128ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 06:31:28,421 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 581444ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 06:31:28,820 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 581453ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 06:31:28,822 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 581444ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 06:31:28,822 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 581441ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 06:41:30,443 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 581095ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 06:41:30,444 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 581096ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 06:41:30,445 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 581097ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 06:41:30,445 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 581096ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 06:51:33,457 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582598ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 06:51:33,500 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582241ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 06:51:33,505 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582171ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 06:51:33,506 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582171ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 07:01:36,380 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582363ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 07:01:36,390 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582211ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 07:01:36,390 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582211ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 07:01:36,415 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582501ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 07:11:39,467 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582225ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 07:11:39,470 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582316ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 07:11:39,471 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582315ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 07:11:39,477 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582214ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 07:21:41,237 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 581262ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 07:21:41,238 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 581262ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 07:21:41,239 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 581464ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 07:21:41,239 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 581464ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 07:31:44,253 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582768ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 07:31:44,256 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582759ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 07:31:44,263 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582758ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 07:31:44,263 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582757ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 07:41:46,331 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 581692ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 07:41:46,635 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 581692ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 07:41:46,636 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 581691ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 07:41:46,639 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 581025ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 07:51:49,447 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 582201ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 07:51:49,449 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 581955ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 07:51:49,460 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 581961ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 07:51:49,481 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 581962ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 08:01:51,570 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 581359ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 08:01:51,571 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 581322ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 08:01:51,571 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 581322ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 08:01:51,572 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 581321ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 08:30:01,270 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 1669437ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 08:30:01,272 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 1669425ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 08:30:01,272 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 1669413ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 08:30:01,498 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 1669459ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 08:41:03,757 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 662101ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 08:41:03,757 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 662095ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 08:41:03,758 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 661926ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 08:41:03,758 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 661639ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 09:08:12,562 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 1608787ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 09:08:12,563 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 1608787ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 09:08:12,569 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 1608786ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 09:08:12,572 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 1608787ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 09:24:32,860 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 960270ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 09:24:32,860 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 960272ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 09:24:32,860 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 960271ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 09:24:32,861 ERROR 58614 nodejs.ClusterClientNoResponseError: client no response in 960268ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 58614
hostname: xingdeMacBook-Pro.local

2018-03-29 09:25:22,869 ERROR 59257 nodejs.ENOENTError: ENOENT: no such file or directory, lstat '/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/config/manifest.json'
ENOENTError: ENOENT: no such file or directory, lstat '/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/config/manifest.json'
errno: -2
code: 'ENOENT'
syscall: 'lstat'
path: '/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/config/manifest.json'
dir: '/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/config'
name: 'ENOENTError'
pid: 59257
hostname: xingdeMacBook-Pro.local

2018-03-29 09:43:27,045 ERROR 59257 nodejs.ClusterClientNoResponseError: client no response in 61945ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 59257
hostname: xingdeMacBook-Pro.local

2018-03-29 09:43:27,045 ERROR 59257 nodejs.ClusterClientNoResponseError: client no response in 61931ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 59257
hostname: xingdeMacBook-Pro.local

2018-03-29 09:43:27,048 ERROR 59257 nodejs.ClusterClientNoResponseError: client no response in 61931ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 59257
hostname: xingdeMacBook-Pro.local

2018-03-29 09:43:27,049 ERROR 59257 nodejs.ClusterClientNoResponseError: client no response in 61932ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 59257
hostname: xingdeMacBook-Pro.local

2018-03-29 10:25:58,219 ERROR 59445 [-/172.16.30.74/-/42ms GET /ssr] nodejs.ReferenceError: resHelpType is not defined
    at SPAController.ssr (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/app/controller/spa.js:14:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

pid: 59445
hostname: xingdeMacBook-Pro.local

2018-03-29 10:26:21,483 ERROR 59448 [-/172.16.30.74/-/50ms GET /ssr] nodejs.ReferenceError: resHelpType is not defined
    at SPAController.ssr (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/app/controller/spa.js:15:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

pid: 59448
hostname: xingdeMacBook-Pro.local

2018-03-29 10:26:43,062 ERROR 59447 [-/172.16.30.74/-/41ms GET /ssr] nodejs.ReferenceError: resHelpType is not defined
    at SPAController.ssr (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/app/controller/spa.js:15:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

pid: 59447
hostname: xingdeMacBook-Pro.local

2018-03-29 10:26:57,574 ERROR 59451 [-/172.16.30.74/-/45ms GET /ssr] nodejs.ReferenceError: resHelpType is not defined
    at SPAController.ssr (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/app/controller/spa.js:14:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

pid: 59451
hostname: xingdeMacBook-Pro.local

2018-03-29 10:29:07,293 ERROR 59467 [-/172.16.30.74/-/44ms GET /ssr] nodejs.TypeError: Cannot read property 'code' of null
    at SPAController.ssr (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/app/controller/spa.js:21:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

pid: 59467
hostname: xingdeMacBook-Pro.local

2018-03-29 10:31:24,353 ERROR 59483 [-/172.16.30.74/-/41ms GET /ssr] nodejs.ReferenceError: res is not defined
    at SPAController.ssr (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/app/controller/spa.js:23:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

pid: 59483
hostname: xingdeMacBook-Pro.local

2018-03-29 10:43:15,313 ERROR 59519 [-/172.16.30.74/-/230ms GET /ssr] nodejs.ReferenceError: document is not defined
    at renderRow (evalmachine.<anonymous>:1071:117)
    at StaticRenderer.render (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/rmc-list-view/lib/ListView.js:78:25)
    at resolve (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/react-dom/cjs/react-dom-server.node.development.js:2149:18)
    at ReactDOMServerRenderer.render (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/react-dom/cjs/react-dom-server.node.development.js:2260:22)
    at ReactDOMServerRenderer.read (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/react-dom/cjs/react-dom-server.node.development.js:2234:19)
    at Object.renderToString (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/react-dom/cjs/react-dom-server.node.development.js:2501:25)
    at Engine.renderToString (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/egg-view-react-ssr/lib/engine.js:62:27)
    at reactElement.then.element (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/egg-view-react-ssr/lib/engine.js:50:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

pid: 59519
hostname: xingdeMacBook-Pro.local

2018-03-29 11:38:14,349 ERROR 59257 nodejs.ClusterClientNoResponseError: client no response in 565488ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 59257
hostname: xingdeMacBook-Pro.local

2018-03-29 11:38:14,350 ERROR 59257 nodejs.ClusterClientNoResponseError: client no response in 565463ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 59257
hostname: xingdeMacBook-Pro.local

2018-03-29 11:38:14,351 ERROR 59257 nodejs.ClusterClientNoResponseError: client no response in 565448ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 59257
hostname: xingdeMacBook-Pro.local

2018-03-29 11:38:14,351 ERROR 59257 nodejs.ClusterClientNoResponseError: client no response in 565393ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 59257
hostname: xingdeMacBook-Pro.local

2018-03-29 11:55:15,080 ERROR 59257 nodejs.ClusterClientNoResponseError: client no response in 1000715ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 59257
hostname: xingdeMacBook-Pro.local

2018-03-29 11:55:15,081 ERROR 59257 nodejs.ClusterClientNoResponseError: client no response in 1000720ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 59257
hostname: xingdeMacBook-Pro.local

2018-03-29 11:55:15,082 ERROR 59257 nodejs.ClusterClientNoResponseError: client no response in 1000716ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 59257
hostname: xingdeMacBook-Pro.local

2018-03-29 11:55:15,082 ERROR 59257 nodejs.ClusterClientNoResponseError: client no response in 1000715ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 59257
hostname: xingdeMacBook-Pro.local

2018-03-29 12:22:21,230 ERROR 59626 [-/172.16.30.74/-/64ms GET /ssr] nodejs.ReferenceError: document is not defined
    at renderRow (evalmachine.<anonymous>:1102:117)
    at StaticRenderer.render (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/rmc-list-view/lib/ListView.js:78:25)
    at resolve (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/react-dom/cjs/react-dom-server.node.development.js:2149:18)
    at ReactDOMServerRenderer.render (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/react-dom/cjs/react-dom-server.node.development.js:2260:22)
    at ReactDOMServerRenderer.read (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/react-dom/cjs/react-dom-server.node.development.js:2234:19)
    at Object.renderToString (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/react-dom/cjs/react-dom-server.node.development.js:2501:25)
    at Engine.renderToString (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/egg-view-react-ssr/lib/engine.js:62:27)
    at reactElement.then.element (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/egg-view-react-ssr/lib/engine.js:50:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

pid: 59626
hostname: xingdeMacBook-Pro.local

2018-03-29 15:52:54,299 ERROR 59257 nodejs.ClusterClientNoResponseError: client no response in 1818077ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 59257
hostname: xingdeMacBook-Pro.local

2018-03-29 15:52:54,300 ERROR 59257 nodejs.ClusterClientNoResponseError: client no response in 1818050ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 59257
hostname: xingdeMacBook-Pro.local

2018-03-29 15:52:54,301 ERROR 59257 nodejs.ClusterClientNoResponseError: client no response in 1818012ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 59257
hostname: xingdeMacBook-Pro.local

2018-03-29 15:52:54,302 ERROR 59257 nodejs.ClusterClientNoResponseError: client no response in 1818051ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 59257
hostname: xingdeMacBook-Pro.local

2018-03-29 16:05:51,725 ERROR 59257 nodejs.ClusterClientNoResponseError: client no response in 717391ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 59257
hostname: xingdeMacBook-Pro.local

2018-03-29 16:05:51,725 ERROR 59257 nodejs.ClusterClientNoResponseError: client no response in 717391ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 59257
hostname: xingdeMacBook-Pro.local

2018-03-29 16:05:51,726 ERROR 59257 nodejs.ClusterClientNoResponseError: client no response in 717391ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 59257
hostname: xingdeMacBook-Pro.local

2018-03-29 16:05:51,726 ERROR 59257 nodejs.ClusterClientNoResponseError: client no response in 717391ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 59257
hostname: xingdeMacBook-Pro.local

2018-03-29 16:54:44,130 ERROR 60313 [-/172.16.30.74/-/23ms GET /ssr] nodejs.ReferenceError: typeListScrollTopUpdate is not defined
    at Object.<anonymous> (evalmachine.<anonymous>:1710:28)
    at __webpack_require__ (evalmachine.<anonymous>:21:30)
    at Object.<anonymous> (evalmachine.<anonymous>:2865:92)
    at __webpack_require__ (evalmachine.<anonymous>:21:30)
    at Object.<anonymous> (evalmachine.<anonymous>:2750:80)
    at __webpack_require__ (evalmachine.<anonymous>:21:30)
    at evalmachine.<anonymous>:64:18
    at evalmachine.<anonymous>:67:10
    at /Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/egg-webpack-react/app.js:23:37
    at Generator.next (<anonymous>)

pid: 60313
hostname: xingdeMacBook-Pro.local

2018-03-29 17:49:22,266 ERROR 60433 A client (undefined:NaN) error [ECONNRESET] occurred: read ECONNRESET
2018-03-29 21:20:40,250 ERROR 61016 nodejs.ClusterClientNoResponseError: client no response in 225537ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 61016
hostname: xingdeMacBook-Pro.local

2018-03-29 21:20:40,255 ERROR 61016 nodejs.ClusterClientNoResponseError: client no response in 225556ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 61016
hostname: xingdeMacBook-Pro.local

2018-03-29 21:20:40,257 ERROR 61016 nodejs.ClusterClientNoResponseError: client no response in 225537ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 61016
hostname: xingdeMacBook-Pro.local

2018-03-29 21:20:40,258 ERROR 61016 nodejs.ClusterClientNoResponseError: client no response in 225526ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 61016
hostname: xingdeMacBook-Pro.local

2018-03-29 21:49:46,022 ERROR 61016 nodejs.ClusterClientNoResponseError: client no response in 1745753ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 61016
hostname: xingdeMacBook-Pro.local

2018-03-29 21:49:46,022 ERROR 61016 nodejs.ClusterClientNoResponseError: client no response in 1745750ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 61016
hostname: xingdeMacBook-Pro.local

2018-03-29 21:49:46,023 ERROR 61016 nodejs.ClusterClientNoResponseError: client no response in 1745748ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 61016
hostname: xingdeMacBook-Pro.local

2018-03-29 21:49:46,024 ERROR 61016 nodejs.ClusterClientNoResponseError: client no response in 1745747ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 61016
hostname: xingdeMacBook-Pro.local

2018-03-29 22:05:18,820 ERROR 61016 nodejs.ClusterClientNoResponseError: client no response in 912785ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 61016
hostname: xingdeMacBook-Pro.local

2018-03-29 22:05:18,820 ERROR 61016 nodejs.ClusterClientNoResponseError: client no response in 912785ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 61016
hostname: xingdeMacBook-Pro.local

2018-03-29 22:25:09,796 ERROR 61016 nodejs.ClusterClientNoResponseError: client no response in 1170966ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 61016
hostname: xingdeMacBook-Pro.local

2018-03-29 22:25:09,796 ERROR 61016 nodejs.ClusterClientNoResponseError: client no response in 1170965ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 61016
hostname: xingdeMacBook-Pro.local

2018-03-29 22:25:09,797 ERROR 61016 nodejs.ClusterClientNoResponseError: client no response in 1170966ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 61016
hostname: xingdeMacBook-Pro.local

2018-03-29 22:25:09,798 ERROR 61016 nodejs.ClusterClientNoResponseError: client no response in 1170966ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 61016
hostname: xingdeMacBook-Pro.local

2018-03-29 22:25:44,983 ERROR 61093 [-/192.168.1.101/-/5026ms GET /ssr] nodejs.ConnectionTimeoutError: Connect timeout for 5000ms, GET http://192.168.2.237:8064/help-app/phone/type -2 (connected: false, keepalive socket: false, agent status: {"createSocketCount":1,"createSocketErrorCount":0,"closeSocketCount":1,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{},"requests":{}})
headers: {}
headers: {}
    at Timeout._onTimeout (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/urllib/lib/urllib.js:755:15)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ConnectionTimeoutError'
requestId: 1
data: undefined
path: '/help-app/phone/type?appName=4&pageSize=20&pageIndex=1'
status: -2
headers: {}
res: { status: -2, statusCode: -2, headers: {}, size: 0, aborted: false, rt: 5011, keepAliveSocket: false, data: undefined, requestUrls: [ 'http://192.168.2.237:8064/help-app/phone/type' ], timing: null, remoteAddress: '', remotePort: '' }
pid: 61093
hostname: xingdeMacBook-Pro.local

2018-03-29 22:28:52,830 ERROR 61092 [-/192.168.1.101/-/5021ms GET /ssr] nodejs.ConnectionTimeoutError: Connect timeout for 5000ms, GET http://192.168.2.237:8064/help-app/phone/type -2 (connected: false, keepalive socket: false, agent status: {"createSocketCount":1,"createSocketErrorCount":0,"closeSocketCount":1,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{},"requests":{}})
headers: {}
headers: {}
    at Timeout._onTimeout (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/urllib/lib/urllib.js:755:15)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ConnectionTimeoutError'
requestId: 1
data: undefined
path: '/help-app/phone/type?appName=4&pageSize=20&pageIndex=1'
status: -2
headers: {}
res: { status: -2, statusCode: -2, headers: {}, size: 0, aborted: false, rt: 5007, keepAliveSocket: false, data: undefined, requestUrls: [ 'http://192.168.2.237:8064/help-app/phone/type' ], timing: null, remoteAddress: '', remotePort: '' }
pid: 61092
hostname: xingdeMacBook-Pro.local

2018-03-29 22:28:56,930 ERROR 61092 [-/192.168.1.101/-/4025ms GET /ssr] nodejs.RequestError: connect ENETUNREACH 192.168.2.237:8064 (req "error"), GET http://192.168.2.237:8064/help-app/phone/type -1 (connected: false, keepalive socket: false, agent status: {"createSocketCount":2,"createSocketErrorCount":0,"closeSocketCount":1,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{"192.168.2.237:8064:":1},"requests":{}})
headers: {}
    at Object._errnoException (util.js:1041:11)
    at _exceptionWithHostPort (util.js:1064:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1153:14)
code: 'ENETUNREACH'
errno: 'ENETUNREACH'
syscall: 'connect'
address: '192.168.2.237'
port: 8064
name: 'RequestError'
data: undefined
path: '/help-app/phone/type?appName=4&pageSize=20&pageIndex=1'
status: -1
headers: {}
res: { status: -1, statusCode: -1, headers: {}, size: 0, aborted: false, rt: 4020, keepAliveSocket: false, data: undefined, requestUrls: [ 'http://192.168.2.237:8064/help-app/phone/type' ], timing: null, remoteAddress: '', remotePort: '' }
headerSent: true
pid: 61092
hostname: xingdeMacBook-Pro.local

2018-03-29 22:28:57,003 ERROR 61091 [-/192.168.1.101/-/4043ms GET /ssr] nodejs.RequestError: connect ENETUNREACH 192.168.2.237:8064 (req "error"), GET http://192.168.2.237:8064/help-app/phone/type -1 (connected: false, keepalive socket: false, agent status: {"createSocketCount":1,"createSocketErrorCount":0,"closeSocketCount":0,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{"192.168.2.237:8064:":1},"requests":{}})
headers: {}
    at Object._errnoException (util.js:1041:11)
    at _exceptionWithHostPort (util.js:1064:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1153:14)
code: 'ENETUNREACH'
errno: 'ENETUNREACH'
syscall: 'connect'
address: '192.168.2.237'
port: 8064
name: 'RequestError'
data: undefined
path: '/help-app/phone/type?appName=4&pageSize=20&pageIndex=1'
status: -1
headers: {}
res: { status: -1, statusCode: -1, headers: {}, size: 0, aborted: false, rt: 4022, keepAliveSocket: false, data: undefined, requestUrls: [ 'http://192.168.2.237:8064/help-app/phone/type' ], timing: null, remoteAddress: '', remotePort: '' }
pid: 61091
hostname: xingdeMacBook-Pro.local

2018-03-29 22:29:16,531 ERROR 61092 [-/192.168.1.101/-/5006ms GET /ssr] nodejs.ConnectionTimeoutError: Connect timeout for 5000ms, GET http://192.168.2.237:8064/help-app/phone/type -2 (connected: false, keepalive socket: false, agent status: {"createSocketCount":3,"createSocketErrorCount":0,"closeSocketCount":3,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{},"requests":{}})
headers: {}
headers: {}
    at Timeout._onTimeout (/Users/xingding/Documents/works/goodsogood/union/chongqing/projects/mobile/ssr-single-help-new/node_modules/urllib/lib/urllib.js:755:15)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ConnectionTimeoutError'
requestId: 3
data: undefined
path: '/help-app/phone/type?appName=4&pageSize=20&pageIndex=1'
status: -2
headers: {}
res: { status: -2, statusCode: -2, headers: {}, size: 0, aborted: false, rt: 5006, keepAliveSocket: false, data: undefined, requestUrls: [ 'http://192.168.2.237:8064/help-app/phone/type' ], timing: null, remoteAddress: '', remotePort: '' }
pid: 61092
hostname: xingdeMacBook-Pro.local

2018-03-29 22:29:52,859 ERROR 61091 [-/192.168.1.101/-/4014ms GET /ssr] nodejs.RequestError: connect ENETUNREACH 192.168.2.237:8064 (req "error"), GET http://192.168.2.237:8064/help-app/phone/type -1 (connected: false, keepalive socket: false, agent status: {"createSocketCount":2,"createSocketErrorCount":0,"closeSocketCount":1,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{"192.168.2.237:8064:":1},"requests":{}})
headers: {}
    at Object._errnoException (util.js:1041:11)
    at _exceptionWithHostPort (util.js:1064:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1153:14)
code: 'ENETUNREACH'
errno: 'ENETUNREACH'
syscall: 'connect'
address: '192.168.2.237'
port: 8064
name: 'RequestError'
data: undefined
path: '/help-app/phone/type?appName=4&pageSize=20&pageIndex=1'
status: -1
headers: {}
res: { status: -1, statusCode: -1, headers: {}, size: 0, aborted: false, rt: 4012, keepAliveSocket: false, data: undefined, requestUrls: [ 'http://192.168.2.237:8064/help-app/phone/type' ], timing: null, remoteAddress: '', remotePort: '' }
pid: 61091
hostname: xingdeMacBook-Pro.local

2018-03-29 23:08:19,188 ERROR 61121 A client (undefined:NaN) error [EPIPE] occurred: write EPIPE
2018-03-29 23:14:43,342 ERROR 61122 A client (undefined:NaN) error [ECONNRESET] occurred: read ECONNRESET
